### PR TITLE
Upgrade Projects to .NET 6

### PR DESCRIPTION
**Pull request by FaisalAfroz**

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
Great!  Besides the failing build, the only thing I'd like to see added is a new test solution that still uses `net5.0`, to verify that the test runner will still work on old solutions.

**Comment by FaisalAfroz** [comment]
Ok I will do a PR with half .net5 and half .net6 .

**Comment by FaisalAfroz** [comment]
See #88  . It have both old and new projects.

**Comment by ErikSchierboom** [comment]
@FaisalAfroz I'd rather update all projects to .net6 and add a new test solution for .net5.

**Comment by ErikSchierboom** [comment]
Even though the CI seems to be passing, it looks like it actually is not: https://github.com/exercism/csharp-test-runner/runs/4163010359?check_suite_focus=true

**Comment by ErikSchierboom** [comment]
@FaisalAfroz The tests still fail: https://github.com/exercism/csharp-test-runner/pull/85/checks Something has changed with powershell in one of the updates. A failure in the tests should result in a failing CI. Something to fix in a separate PR.

**Comment by FaisalAfroz** [comment]
Yes, I think that is another issue. If a build fails it should indicate red instead of green.

**Comment by ErikSchierboom** [comment]
Let me know when you've managed to fix the build

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Merged! Thanks a lot.

**Pull request merged**
