### PR TITLE
Make deploy.yml copy-pastable

### PR DESCRIPTION
**Pull request by SaschaMann**
Test here: https://github.com/SaschaMann/csharp-test-runner/actions/runs/324616921

### CODE REVIEW

**Comment by SaschaMann** [comment]
This allows one to just copy it to a track instead of requiring manual edits.

**Comment by iHiD** [comment]
Great idea!

**Comment by SleeplessByte** [comment]
Jealous

**Comment by ErikSchierboom** [comment]
Awesome idea!

**Pull request merged**
